import Header from '@/components/Header'
import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="">
      <body
        className={
          rubik.className +
          'bg-secondary-100 dark:bg-primary-700 text-primary-700 dark:text-secondary-100'
        }
      >
        <Header />
        <main>{children}</main>
      </body>
    </html>
  )
}
